# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcicle',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
